### ISSUE TITLE
有报错attribute 'queue' of 'gevent._queue.Queue' objects is not writable

### ISSUE THREAD

**Issue by littleheary** [blackye/webdirdig#2]
运行到一半的时候就会报错，提示
Traceback (most recent call last):
  File "webdirdig.py", line 14, in <module>
    if __name__ == '__main__': main()
  File "webdirdig.py", line 11, in main
    Controller(sys.argv[1])
  File "/soft/web/webdirdig/lib/controller/controller.py", line 48, in __init__
    self.run()
  File "/soft/web/webdirdig/lib/controller/controller.py", line 59, in run
    self.scanner.start()
  File "/soft/web/webdirdig/lib/controller/scanner.py", line 55, in start
    self.start_webfile_scan()
  File "/soft/web/webdirdig/lib/controller/scanner.py", line 151, in start_webfile_scan
    self.exist_sensi_que.queue = deepcopy(self.exist_dir_que.queue)
AttributeError: attribute 'queue' of 'gevent._queue.Queue' objects is not writable

**Comment by ASDWQad** [comment]
同样。

**Comment by im23pds** [comment]
the same @blackye

**Comment by Missname** [comment]
同

**Comment by hahadoge** [comment]
+1
